#!/bin/bash
set -e

# Maven version helpers for Java/Spring Boot projects
# Reads and increments version from pom.xml

get_pom_version() {
    local version
    version=$(mvn -s ci_settings.xml help:evaluate -Dexpression=project.version -q -DforceStdout 2>/dev/null)
    if [ $? -ne 0 ]; then
        echo "Error: Maven command failed."
        exit 1
    fi
    echo "$version"
}

get_new_version() {
    local part_to_increment=$1
    local version=$(get_pom_version)
    IFS='.' read -r major minor patch <<< "$version"

    case $part_to_increment in
        major) major=$((major + 1)); minor=0; patch=0 ;;
        minor) minor=$((minor + 1)); patch=0 ;;
        patch) patch=$((patch + 1)) ;;
        *) echo "Error: must be 'major', 'minor', or 'patch'."; exit 1 ;;
    esac

    echo "$major.$minor.$patch"
}

increment_version() {
    local part_to_increment=$1
    local version=$(get_pom_version)
    echo "Current version: $version"

    local new_version=$(get_new_version "$part_to_increment")
    echo "New version: $new_version"

    # Update pom.xml (processAllModules for multi-module projects)
    mvn -s ci_settings.xml versions:set -DnewVersion="$new_version" -DprocessAllModules=true -q
    if [ $? -ne 0 ]; then
        echo "Error: Failed to update POM version."
        exit 1
    fi

    # Remove backup files generated by versions:set
    mvn -s ci_settings.xml versions:commit -q 2>/dev/null || true

    echo "Version updated to $new_version in pom.xml"
}
